### ISSUE TITLE
Registration no include auth cookies.

### ISSUE THREAD

**Issue by teamhashed-admin** [whoismaruf/drauth#8]
**Describe the bug**
After registration, it doesn't set cookies for authentication. It causes the user forced to login after successful registration.

**To Reproduce**
1. Go to `api/auth/registration/`
2. Try to register with credentials
3. Watch the `cookies`
4. See, no access or refresh tokens

**Expected behavior**
It should set the authentication cookies after registration and logged the user instantly.

**Screenshots**

![image](https://user-images.githubusercontent.com/62182152/196447012-4cb337c3-b71f-4b90-bf84-4f56b3fa562a.png)

**Comment by whoismaruf** [comment]
Need to create a custom `Registration` view.
